# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f3f64d1e539746ea1331f816ddb1855181f30ab911187688228383a66c76717650bfb548dcb5046b7c68d4944ce8459dc3d4340254a20a6f26fb86274ef195f

test:
  secret_key_base: c1e96b4b51242954272f36e1cad73674d775639bba446fc6adb6e26f36d1a93e3e80042856caf145c25ae9ba76aa17906108b91ea94cd89110afc462510e05a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
